
version: '4'

services:
  mongo-card-creator:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: carnetizacionOpera003
    volumes:
      - ./db/card-creator:/data/db

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_registro
    user: root
    expose:
      - 1433
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "5dZ8psbVg7mp6M"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      HOSTNAME: 192.168.98.20
    volumes:
       - ./db/mssql:/var/opt/mssql